# Allow build scripts to be referenced without being copied into the final image
FROM scratch AS ctx
COPY build_files /
COPY system_files /system_files

FROM ghcr.io/ublue-os/akmods:ogc-44 AS akmods
FROM ghcr.io/ublue-os/akmods-nvidia-open:ogc-44 AS akmods-nvidia

FROM ghcr.io/ublue-os/aurora-nvidia-open@sha256:ff6de73c02a85fdfdf0a79a1004db155d176e809b4b18a68fe3a7dbefec9feab

COPY --from=ghcr.io/ublue-os/brew:latest /system_files /

RUN rm -rf /opt && mkdir /opt
RUN mkdir -p /usr/share/ublue-os/homebrew/
COPY brew/packages-edward.Brewfile /usr/share/ublue-os/homebrew/packages.Brewfile

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=bind,from=akmods,src=/kernel-rpms,dst=/tmp/kernel-rpms \
    --mount=type=bind,from=akmods-nvidia,src=/rpms,dst=/tmp/akmods-nvidia \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build-edward.sh

RUN /usr/bin/systemctl preset brew-setup.service && \
    /usr/bin/systemctl preset brew-update.timer && \
    /usr/bin/systemctl preset brew-upgrade.timer && \
    /usr/bin/systemctl preset brew-bundle-packages.service

RUN rm -rf /run/dnf /run/setrans /tmp/*
RUN rm -rf /usr/etc
RUN bootc container lint
