FROM blueprint-arch:latest AS ctx
COPY build_files /
COPY system_files.holo /system_files.holo

FROM blueprint-arch:latest

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache/pacman/pkg \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build-holo.sh

RUN bootc container lint
