FROM scratch AS ctx
COPY build_files /
COPY system_files /system_files

FROM quay.io/fedora/fedora:44 AS steam-sysext

COPY systext/steam /steam-src
RUN chmod +x /steam-src/build.sh && /steam-src/build.sh

FROM ghcr.io/ublue-os/aurora-nvidia-open:stable

COPY --from=ghcr.io/ublue-os/brew:latest /system_files /

RUN rm -rf /opt && mkdir /opt
RUN mkdir -p /usr/share/ublue-os/homebrew/
COPY brew/packages-edward.Brewfile /usr/share/ublue-os/homebrew/packages.Brewfile

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=bind,from=steam-sysext,src=/sysext,dst=/tmp/steam-sysext \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build-edward.sh

RUN rm -rf /run/dnf /run/setrans /tmp/*
RUN rm -rf /usr/etc
RUN bootc container lint
