# Allow build scripts to be referenced without being copied into the final image
FROM scratch AS ctx
COPY build_files /
COPY system_files.arch /system_files.arch

FROM archlinux:latest AS builder

RUN pacman -Syu --noconfirm \
    base-devel \
    git \
    rust \
    cargo \
    go-md2man \
    ostree \
    glibc \
    pkgconf \
    python-setuptools

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache/pacman/pkg \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build_files/builder-arch.sh

FROM archlinux:latest AS system

COPY --from=builder /output /

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache/pacman/pkg \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build_files/build-arch.sh

LABEL containers.bootc 1

RUN bootc container lint
