# Allow build scripts to be referenced without being copied into the final image
FROM scratch AS ctx
COPY build_files /
COPY system_files /system_files
RUN mkdir -p /usr/share/ublue-os/homebrew/
COPY brew/packages-edward.Brewfile /usr/share/ublue-os/homebrew/packages.Brewfile

FROM ghcr.io/ublue-os/akmods:ogc-44 AS akmods
FROM ghcr.io/ublue-os/akmods-nvidia-open:ogc-44 AS akmods-nvidia


FROM ghcr.io/projectbluefin/bluefin-nvidia@sha256:ff1a9c6e5cd5ae2a69133aa3f8aa0d634d123392a977747de2e81e22b4097f20

COPY --from=ghcr.io/ublue-os/brew:latest /system_files /

RUN rm -rf /opt && mkdir /opt

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=bind,from=akmods,src=/kernel-rpms,dst=/tmp/kernel-rpms \
    --mount=type=bind,from=akmods-nvidia,src=/rpms,dst=/tmp/akmods-nvidia \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build-edward.sh

RUN rm -rf /run/dnf /run/setrans /tmp/*
RUN rm -rf /usr/etc
RUN bootc container lint
