#!/usr/bin/env bash
set -xeuo pipefail

IMAGE_INFO="/usr/share/ublue-os/image-info.json"

if [ -n "${IMAGE_NAME:-}" ] && [ -n "${IMAGE_REF:-}" ]; then
    tee "$IMAGE_INFO" <<EOF
{
  "image-name": "${IMAGE_NAME}",
  "image-ref": "${IMAGE_REF}",
  "image-flavor": "main",
  "image-vendor": "${IMAGE_VENDOR:-huntedraven7}",
  "image-tag": "stable/testing",
  "almalinux-version": "${MAJOR_VERSION_NUMBER:-10}"
}
EOF
    chmod 0644 "${IMAGE_INFO}"
fi
