# Allow build scripts to be referenced without being copied into the final image
FROM scratch AS ctx
COPY build_files /
COPY buildstream/build_files/fsdk /build_files/fsdk
COPY system_files/global /system_files/global
COPY system_files/fsdk /system_files/fsdk

FROM ghcr.io/huntedraven7/blueprint:ubuntu AS builder

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        python3 \
        python3-pip \
        jq \
        yq \
        gh \
        skopeo \
        buildah \
        podman \
        docker.io \
        ostree

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=tmpfs,dst=/tmp \
    --mount=type=tmpfs,dst=/root \
    --mount=type=tmpfs,dst=/boot \
    git clone "https://github.com/bootc-dev/bootc.git" /tmp/bootc && \
    make -C /tmp/bootc bin install-all DESTDIR=/output && \
    rm -rf /tmp/bootc

FROM ghcr.io/huntedraven7/blueprint:ubuntu AS system

COPY --from=builder /output /

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build_files/fsdk/build.sh

LABEL containers.bootc 1
