# Allow build scripts to be referenced without being copied into the final image
FROM scratch AS ctx
COPY build_files /
COPY system_files/global /system_files/global
COPY system_files/gentoo /system_files/gentoo

FROM gentoo/stage3:systemd AS builder

RUN mkdir -p /etc/portage/binrepos.conf && \
    printf '[gentoo]\npriority = 9959\nsync-uri = https://distfiles.gentoo.org/releases/amd64/binpackages/23.0/x86-64/\nverify-signature = false\nlocation = /var/cache/binhost/gentoo\n' > /etc/portage/binrepos.conf/gentoo.conf && \
    echo "FEATURES=\"-manifest getbinpkg binpkg-multi-instance binpkg-request-signature parallel-fetch parallel-install\"" >> /etc/portage/make.conf && \
    echo "MAKEOPTS=\"-j$(nproc)\"" >> /etc/portage/make.conf && \
    echo "EMERGE_DEFAULT_OPTS=\"--getbinpkg\"" >> /etc/portage/make.conf && \
    getuto && \
    emerge --getbinpkg --verbose dev-util/ostree net-misc/openssh sys-devel/gcc dev-util/pkgconf dev-vcs/git app-arch/cpio app-arch/xz-utils app-arch/bzip2 dev-go/go-md2man

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/base/builder-gentoo.sh

FROM gentoo/stage3:systemd AS system

COPY --from=builder /output /

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/base/build-gentoo.sh

LABEL containers.bootc 1
