FROM scratch AS ctx
COPY build_files /
COPY system_files.holo /system_files.holo

FROM blueprint:arch

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build-holo-nvidia.sh

RUN bootc container lint

LABEL containers.bootc 1
