# Allow build scripts to be referenced without being copied into the final image
FROM scratch AS ctx
COPY build_files /
COPY system_files/global /system_files/global
COPY system_files/gentoo /system_files/gentoo

FROM gentoo/stage3:systemd AS builder

RUN echo 'FEATURES="-manifest binpkg-multi-instance binpkg-signing"' >> /etc/portage/make.conf && \
    echo 'EMERGE_DEFAULT_OPTS="--getbinpkg"' >> /etc/portage/make.conf && \
    emerge --sync --quiet && \
    emerge --getbinpkg --verbose dev-util/ostree net-misc/openssh sys-devel/gcc dev-util/pkgconf dev-vcs/git app-arch/cpio app-arch/xz-utils app-arch/bzip2

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/base/builder-gentoo.sh

FROM gentoo/stage3:systemd AS system

COPY --from=builder /output /

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/base/build-gentoo.sh

LABEL containers.bootc 1
