# Allow build scripts to be referenced without being copied into the final image
FROM scratch AS ctx
COPY build_files /
COPY system_files/global /system_files/global
COPY system_files/ubuntu /system_files/ubuntu

FROM ubuntu:26.04 AS builder

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        git \
        make \
        build-essential \
        go-md2man \
        libzstd-dev \
        pkgconf \
        libostree-dev \
        ostree

ENV CARGO_HOME=/tmp/rust
ENV RUSTUP_HOME=/tmp/rust
ENV PATH=/tmp/rust/bin:${PATH}

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=tmpfs,dst=/tmp \
    --mount=type=tmpfs,dst=/root \
    --mount=type=tmpfs,dst=/boot \
    curl --proto '=https' --tlsv1.2 -sSf "https://sh.rustup.rs" | sh -s -- --profile minimal -y && \
    /ctx/base/builder-ubuntu.sh

FROM ubuntu:26.04 AS system

COPY --from=builder /output /

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/base/build-ubuntu.sh

LABEL containers.bootc 1

RUN bootc container lint
