# Allow build scripts to be referenced without being copied into the final image
FROM scratch AS ctx
COPY build_files /
COPY system_files/global /system_files/global
COPY system_files/nixos /system_files/nixos

FROM nixos/nix:latest AS builder

RUN nix-channel --update && \
    nix-channel --add https://nixos.org/channels/nixos-26.05 nixos && \
    nix-channel --update && \
    nix-env -iA nixpkgs.bootc && \
    nix-env -iA nixpkgs.git && \
    nix-env -iA nixpkgs.curl && \
    nix-env -iA nixpkgs.ostree

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build_files/nixos/build.sh

FROM nixos/nix:latest AS system

COPY --from=builder /output /

LABEL containers.bootc 1
