# Allow build scripts to be referenced without being copied into the final image
FROM scratch AS ctx
COPY build_files /
COPY system_files/global /system_files/global
COPY system_files/debian /system_files/debian

FROM docker.io/library/debian:trixie AS builder

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        git \
        curl \
        make \
        build-essential \
        go-md2man \
        libzstd-dev \
        pkgconf \
        dracut \
        libostree-dev \
        ostree

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=tmpfs,dst=/tmp \
    --mount=type=tmpfs,dst=/root \
    --mount=type=tmpfs,dst=/boot \
    /ctx/builder-debian.sh

FROM docker.io/library/debian:trixie AS system

COPY --from=builder /output /

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=tmpfs,dst=/tmp \
    --mount=type=tmpfs,dst=/root \
    --mount=type=tmpfs,dst=/boot \
    /ctx/build-debian.sh

LABEL containers.bootc 1
