ARG BREW_IMAGE_REF

FROM ${BREW_IMAGE_REF} AS brew

FROM scratch AS ctx

COPY --from=brew /system_files /files
COPY system_files /files
COPY brew /brew
COPY build_files/edward /build_scripts
COPY image-versions.yaml /image-versions.yaml

FROM quay.io/almalinuxorg/almalinux-bootc@sha256:cdbd976f38d0e58b8e42252f925c997116c51c06fb8fe1bd2057f9c3474fb4bf

ARG ENABLE_DX="${ENABLE_DX:-0}"
ARG ENABLE_NVIDIA="${ENABLE_NVIDIA:-1}"
ARG GNOME_VERSION="${GNOME_VERSION:-50}"
ARG IMAGE_NAME="${IMAGE_NAME:-edward}"
ARG IMAGE_VENDOR="${IMAGE_VENDOR:-huntedraven7}"
ARG MAJOR_VERSION="${MAJOR_VERSION:-10}"
ARG SHA_HEAD_SHORT="${SHA_HEAD_SHORT:-deadbeef}"

RUN --mount=type=tmpfs,dst=/opt \
  --mount=type=tmpfs,dst=/tmp \
  --mount=type=tmpfs,dst=/var \
  --mount=type=tmpfs,dst=/boot \
  --mount=type=bind,from=ctx,source=/,target=/run/context \
  /run/context/build_scripts/build.sh

RUN rm -rf /opt && ln -s /var/opt /opt

LABEL containers.bootc 1
RUN bootc container lint
