FROM scratch AS ctx
COPY build_files /
COPY system_files/global /system_files/global
COPY system_files/dakota /system_files/dakota

FROM ghcr.io/projectbluefin/dakota:testing

COPY brew/packages-dakota.Brewfile /usr/share/ublue-os/homebrew/preinstall.d/packages-dakota.Brewfile

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build-dakota.sh

RUN bootc container lint
