name: Renovate

on:
  schedule:
    - cron: '0 4 * * 1' # 4:00am UTC every Monday
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Renovate
        uses: renovatebot/github-action@46c83f70d777d7dd116cfe07681a41dc8d3e2e9d # v41
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN || secrets.GITHUB_TOKEN }}
